AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pontius Pilates website infrastructure - S3 bucket with CloudFront distribution

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging

Globals:
  Function:
    Timeout: 30
    Runtime: python3.13

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub pontius-pilates-website-${Environment}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${WebsiteBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub pontius-pilates-oac-${Environment}
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2and3
        PriceClass: PriceClass_100
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          Compress: true
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /404.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
            ErrorCachingMinTTL: 300

  # SSM Parameters for storing infrastructure values
  S3BucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /pontius-pilates/${Environment}/s3-bucket-name
      Type: String
      Value: !Ref WebsiteBucket
      Description: S3 bucket name for the website

  CloudFrontDistributionIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /pontius-pilates/${Environment}/cloudfront-distribution-id
      Type: String
      Value: !Ref CloudFrontDistribution
      Description: CloudFront distribution ID

  CloudFrontDomainParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /pontius-pilates/${Environment}/cloudfront-domain
      Type: String
      Value: !GetAtt CloudFrontDistribution.DomainName
      Description: CloudFront distribution domain name

Outputs:
  WebsiteBucketName:
    Description: S3 bucket name
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub ${AWS::StackName}-BucketName

  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub ${AWS::StackName}-DistributionId

  CloudFrontDomain:
    Description: CloudFront distribution domain
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub ${AWS::StackName}-Domain

  WebsiteUrl:
    Description: Website URL
    Value: !Sub https://${CloudFrontDistribution.DomainName}
